// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("API.Entities.MtoEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BaseWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<float>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<string>("DwgCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DwgNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatGroup")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatType")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatVariant")
                        .HasColumnType("TEXT");

                    b.Property<float>("Nal")
                        .HasColumnType("REAL");

                    b.Property<string>("PlatArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StructArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("StructType")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubArea")
                        .HasColumnType("TEXT");

                    b.Property<float>("SurfaceArea")
                        .HasColumnType("REAL");

                    b.Property<float>("Thickness")
                        .HasColumnType("REAL");

                    b.Property<float>("UnitWeight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("API.Entities.MtoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownAs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
